### PR TITLE
Fix compilation with Linux 5.18-rc1

### LINKED ISSUE #17: Build fails linking with 5.18-rc1
When trying to build the module for an [Allwinner D1 kernel](https://github.com/smaeul/linux/tree/riscv/d1-wip) i get linking errors:
```
  LD [M]  /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/8723ds.o
riscv64-linux-gnu-ld: /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_security.o: in function `is_multicast_mac_addr':
/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_security.c:1924: multiple definition of `is_multicast_mac_addr'; /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_cmd.o:/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_cmd.c:4186: first defined here
riscv64-linux-gnu-ld: /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_security.o: in function `is_broadcast_mac_addr':
/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/include/ieee80211.h:1295: multiple definition of `is_broadcast_mac_addr'; /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_cmd.o:/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/include/ieee80211.h:1295: first defined here
riscv64-linux-gnu-ld: /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_security.o: in function `is_zero_mac_addr':
/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/include/ieee80211.h:1301: multiple definition of `is_zero_mac_addr'; /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_cmd.o:/home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/include/ieee80211.h:1301: first defined here
riscv64-linux-gnu-ld: /home/user/Projects/risc-v-lichee-rv/image_builder/build/rtl8723ds/core/rtw_debug.o: in function `is_multicast_mac_addr':
```
These are repeated many times, i can provide the full log but didn't want to spam too much.
_(It was working fine with 5.17)_

### PR DESCRIPTION
**Pull request by sehraf**
Fixes #17

### CODE REVIEW

**Comment by sehraf** [comment]
fixed already by 76146e85847beb2427b1d4958fa275822f2b04ab
